[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "pets"
username = "user"
password = "user"
#url = "mysql:///pets.db"


[connections.pets_db]
url = "sqlite:///pets.db"